# Generated by Django 3.2 on 2021-09-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alco_species", "0001_add_alcohol_group_and_type_models"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alcoholgroup",
            old_name="parent",
            new_name="parent_group",
        ),
    ]
